### ISSUE TITLE
오늘의 뮤지컬 스케쥴 봇이 2022-07-31을 마지막으로 돌아가지 않는다. 

### ISSUE THREAD

**Issue by leeleelee3264** [leeleelee3264/twitter_project#7]
오늘의 뮤지컬 스케쥴 봇이 2022-07-31을 마지막으로 돌아가지 않는다.
![스크린샷 2022-08-09 오후 2 44 08](https://user-images.githubusercontent.com/35620531/183573340-68c46c5e-8420-4a30-9191-5b6ff23f25d0.png)

**Comment by leeleelee3264** [comment]
디버깅 결과 
- DB에 현재 상영중인 뮤지컬이 쌓이지 않고 있었다. 
- 확인 결과 샐레니움을 위해 서버에 설치된 chromedriver의 호환 버전 문제가 발생하고 있었다. 

```
Traceback (most recent call last):
  File "crawl/dynamic/musical/main_info_parser.py", line 120, in <module>
    crawl()
  File "crawl/dynamic/musical/main_info_parser.py", line 95, in crawl
    _driver = driver.get_driver(headless=True)
  File "/opt/twitter_project/crawl/dynamic/driver.py", line 23, in get_driver
    return wb.Chrome(executable_path=real_path, chrome_options=options)
  File "/opt/twitter_project/twitter/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/opt/twitter_project/twitter/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/twitter_project/twitter/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/twitter_project/twitter/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/twitter_project/twitter/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 94
Current browser version is 102.0.5005.61 with binary path /usr/bin/google-chrome

Traceback (most recent call last):
  File "crawl/dynamic/musical/additional_info_parser.py", line 117, in <module>
    crawl()
  File "crawl/dynamic/musical/additional_info_parser.py", line 60, in crawl
    _driver = driver.get_driver(headless=True)
  File "/opt/twitter_project/crawl/dynamic/driver.py", line 23, in get_driver
    return wb.Chrome(executable_path=real_path, chrome_options=options)
  File "/opt/twitter_project/twitter/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/opt/twitter_project/twitter/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/twitter_project/twitter/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/twitter_project/twitter/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/twitter_project/twitter/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 94
Current browser version is 102.0.5005.61 with binary path /usr/bin/google-chrome

```

**Comment by leeleelee3264** [comment]
![image](https://user-images.githubusercontent.com/35620531/184928494-7244678a-f8a8-408a-9559-863bf503e44d.jpeg)

ubuntu에 깔려있는 기존의 chromedriver를 지우고 맞는 버전의 chromedriver를 내려받아 깔아줬다. 

> 앞으로도 또 이런 일이 발생하면 ubuntu에 설치 되어있는 google-chrome의 자동 업데이트를 막아서 버전 호환 문제가 일어나지 않도록 해야 할 필요가 있다.
